### PR TITLE
Migrate Banner service from deprecated openJDK docker image

### PR DESCRIPTION
**Pull request by SteveScorfield**
# What and why?
There is a requirement to migrate from the deprecated version of openJDK-17 to eclipse. This PR achieves this.

# How to test?
Run unit and acceptance tests in UI.

# Jira
https://jira.ons.gov.uk/browse/RAS-971

### CODE REVIEW

**Review by matthew-robinson-ons — APPROVED** [review]
Changes look good, tests all running.

**Review by arroyoAle — APPROVED** [review]
Code tested with unit tests and image with acceptance tests and setting up a banner - all looks good

**Pull request merged**
